/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyScBoostClk.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBFS.h"
#include "USBFS_audio.h"
#include "USBFS_cdc.h"
#include "USBFS_hid.h"
#include "USBFS_midi.h"
#include "USBFS_pvt.h"
#include "USBFS_cydmac.h"
#include "USBFS_msc.h"
#include "KNAP_aliases.h"
#include "KNAP.h"
#include "PORE_aliases.h"
#include "PORE.h"
#include "xAkse_aliases.h"
#include "xAkse.h"
#include "yAkse_aliases.h"
#include "yAkse.h"
#include "xAksen.h"
#include "yAksen.h"
#include "USBFS_Dm_aliases.h"
#include "USBFS_Dm.h"
#include "USBFS_Dp_aliases.h"
#include "USBFS_Dp.h"
#include "xAksen_IRQ.h"
#include "xAksen_theACLK.h"
#include "xAksen_Bypass_aliases.h"
#include "xAksen_Bypass.h"
#include "yAksen_IRQ.h"
#include "yAksen_theACLK.h"
#include "yAksen_Bypass_aliases.h"
#include "yAksen_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

